# The URL the site will be built for
base_url = "https://hunje.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "hermit_zola"

title = "Hunje Cho"
description = "Mobile Business Card"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

profile_image = "profile.jpg"

home_subtitle = "Software Engineer"

footer_copyright="2023 (c) Hunje Cho"

hermit_menu = [
]

hermit_social = [
    { name = "email", link = "mailto:cho_hunje@cocone.co.jp"},
    { name = "linkedin", link = "https://www.linkedin.com/in/hunje"},
    { name = "github", link = "https://github.com/hunje" },
    { name = "telegram", link = "https://t.me/hunje_mooi" },
    { name = "twitter", link = "https://twitter.com/hunje" },
]

toc=false

[extra.highlightjs]
enable = true
clipboard = true
theme = "vs2015"

[extra.disqus]
enable = false

[extra.author]
name = "Hunje Cho"
email = "cho_hunje@cocone.co.jp"
